'use client';
import {useEffect,useState} from 'react';
const agents=['Researcher','Analyst','Architect','Creator','Builder','Simulator','Auditor','Optimizer','Coordinator','Teacher'];
export default function Home(){const [mission,setMission]=useState('');const [plan,setPlan]=useState<any>(null);const [health,setHealth]=useState<any>(null);const [approval,setApproval]=useState('');
useEffect(()=>{fetch('/api/health').then(r=>r.json()).then(setHealth).catch(()=>null)},[]);
async function run(){const r=await fetch('/api/mission',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mission})});setPlan(await r.json())}
async function approve(decision:'APPROVE'|'REJECT'){if(!plan?.missionId)return;const r=await fetch('/api/approval',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({missionId:plan.missionId,taskId:plan.tasks?.[0]?.id||'mission-plan',decision})});setApproval(JSON.stringify(await r.json(),null,2))}
return <main className="wrap"><header className="top"><div><div className="eyebrow">7¹⁰ • ROOT OS v5.2.5</div><h1 className="title">THE <span className="gold">COMMAND</span><br/>ARCHITECTURE</h1><p className="muted">Command environment • AI • memory • authority • verification</p></div><div><span className="pill">MISSION</span><span className="pill">MEMORY</span><span className="pill">VERIFY</span></div></header>
<section className="grid"><div className="card"><div className="label">01 / Define the mission</div><textarea className="textarea" value={mission} onChange={e=>setMission(e.target.value)} placeholder="What outcome do you want ROOT to produce?"/><div className="actions"><button className="btn" onClick={run} disabled={!mission.trim()}>BUILD PLAN</button></div>{plan&&<><pre className="status">{JSON.stringify(plan,null,2)}</pre><div className="actions"><button className="btn" onClick={()=>approve('APPROVE')}>APPROVE</button><button className="btn secondary" onClick={()=>approve('REJECT')}>REJECT</button></div></>}</div>
<div className="card"><div className="label">02 / Operating team</div>{agents.map(a=><div className="agent" key={a}><span>{a}</span><span className="muted">READY</span></div>)}</div></section>
<section className="grid"><div className="card"><div className="label">03 / Infrastructure readiness</div><p>AI Gateway: <b>{health?.aiGateway?'READY':'CONFIGURE'}</b></p><p>Database: <b>{health?.database?'READY':'OPTIONAL / CONFIGURE'}</b></p><p>Auth: <b>{health?.auth?'READY':'OPTIONAL / CONFIGURE'}</b></p><p>Human authority: <b>ENFORCED</b></p></div><div className="card"><div className="label">04 / Approval ledger</div><pre className="status">{approval||'No approval recorded yet.'}</pre></div></section>
<section className="card"><div className="label">ROOT control law</div><p className="metric">INTENT → REALITY → SCALE</p><p className="muted">Human intent → AI capability → verification → human authority.</p></section></main>}
